FROM continuumio/miniconda3:4.10.3

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

RUN apt-get -y update &&\
  apt-get -y install procps &&\
  apt-get clean

ENV PYTHONUNBUFFERED=1

ENV HOME=/code
WORKDIR ${HOME}

COPY *.py *.nf site_substructures.smarts ./

# conda install our requirements, including RDKit and OpenBabel
RUN conda install -y -c conda-forge pip=21.1.1 rdkit=2021.03.5 openbabel=3.1.1 pdb2pqr=3.2.0 scikit-learn=0.24.2 &&\
  pip install im-standardize-molecule==0.1.0 &&\
  pip install im-data-manager-job-utilities==1.0.1 &&\
  conda init bash

# set the default umask to 002
#RUN sed -i 's/UMASK\t\t022/UMASK\t\t002/' /etc/login.defs
#RUN echo "umask 0002" > /etc/profile.d/umask.sh
