---
version: '3.0'

# Build and push with: -
#
# IMAGE_TAG=1.0.0 docker-compose build
# IMAGE_TAG=1.0.0 docker-compose push

services:

  prep:
    build:
      context: .
      dockerfile: Dockerfile-prep
    image: informaticsmatters/vs-prep:${IMAGE_TAG:-latest}

  nextflow:
    build:
      context: .
      dockerfile: Dockerfile-nextflow
    image: informaticsmatters/vs-nextflow:${IMAGE_TAG:-latest}
    
  rdock:
    build:
      context: .
      dockerfile: Dockerfile-rdock
    image: informaticsmatters/vs-rdock:${IMAGE_TAG:-latest}

  smina:
    build:
      context: .
      dockerfile: Dockerfile-smina
    image: informaticsmatters/vs-smina:${IMAGE_TAG:-latest}

  oddt:
    build:
      context: .
      dockerfile: Dockerfile-oddt
    image: informaticsmatters/vs-oddt:${IMAGE_TAG:-latest}

  plants:
    build:
      context: .
      dockerfile: Dockerfile-plants
    image: informaticsmatters/vs-plants:${IMAGE_TAG:-latest}

  fragnet-search:
    build:
      context: .
      dockerfile: Dockerfile-fns
    image: informaticsmatters/vs-fragnet-search:${IMAGE_TAG:-latest}

  jaqpot:
    build:
      context: .
      dockerfile: Dockerfile-jaqpot
    image: informaticsmatters/vs-jaqpot:${IMAGE_TAG:-latest}

  moldb:
    build:
      context: .
      dockerfile: Dockerfile-moldb
    image: informaticsmatters/vs-moldb:${IMAGE_TAG:-latest}

