FROM informaticsmatters/vs-rdkit-base:latest

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

ENV PYTHONPATH=/code
ENV HOME=/code
WORKDIR ${HOME}

# install our requirements. RDKit is present in base container
RUN pip install pip install mordredcommunity==2.0.4 \
  im-standardize-molecule==0.1.0 \
  im-data-manager-job-utilities==1.1.1

COPY im_mordred/descriptor_calc.py ./im_mordred/
COPY utils.py rdkit_utils.py ./
