FROM informaticsmatters/obabel:3.1.1

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

ENV PYTHONUNBUFFERED=1

ENV HOME=/code
WORKDIR ${HOME}

# Do stuff as root
USER 0
COPY --chown=obabel gen_conformer.* ./
RUN chmod 755 *.py

# Adjust the path
ENV PATH="${PATH}:${HOME}"

# Finally, return to the obabel user id.
USER obabel
