FROM informaticsmatters/rdkit-python3-debian:Release_2021_03_2

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

ENV PYTHONUNBUFFERED=1

ENV HOME=/code
WORKDIR ${HOME}

# Do stuff as root
# partly to allow installed Python packages to be used by anyone
USER 0
COPY --chown=rdkit:root *.py *.nf site_substructures.smarts ./
RUN pip install im-standardize-molecule==0.1.0 && \
    chmod 755 *.py

# Install material to support Nextflow
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        openjdk-11-jre-headless \
        curl \
        git && \
    apt-get clean -y

# Install nextflow
RUN curl -s https://get.nextflow.io | bash && \
    chmod 755 nextflow && \
    mv nextflow /usr/local/bin/

# Adjust permissions for RunAsAnyUser
RUN chmod 777 ${HOME} && \
    chmod 777 ${HOME}/.nextflow && \
    chown -R rdkit:root ${HOME}/.nextflow && \
    find ./.nextflow -type d | xargs chmod 777 && \
    find . -type f -name '*.jar' | xargs chmod 655

# Adjust the path
ENV PATH="${PATH}:${HOME}:/usr/local/bin"

# Finally, return to the RDKit user id.
USER rdkit
