---
version: '3.0'

# Build and push with: -
#
# IMAGE_TAG=1.0.0 docker-compose build
# IMAGE_TAG=1.0.0 docker-compose push

services:

  rdkit:
    build:
      context: .
      dockerfile: Dockerfile-prep
    image: informaticsmatters/vs-prep:${IMAGE_TAG:-latest}

  obabel:
    build:
      context: .
      dockerfile: Dockerfile-nextflow
    image: informaticsmatters/vs-nextflow:${IMAGE_TAG:-latest}
    
  rdock:
    build:
      context: .
      dockerfile: Dockerfile-rdock
    image: informaticsmatters/vs-rdock:${IMAGE_TAG:-latest}
