FROM informaticsmatters/vs-rdkit-base:latest

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

RUN apt-get update && apt-get -y install git &&\
  apt-get clean

ENV PYTHONPATH=/code
ENV HOME=/code
WORKDIR ${HOME}

RUN pip install wheel six &&\
  pip install im-data-manager-job-utilities==1.2.0\
  git+https://github.com/oddt/oddt.git@master

COPY *.py ./