FROM informaticsmatters/vs-rdkit-base:3.0.0

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

# openbabel does not install easily with PIP, and we don't have conda so we must use apt to install.
# this installs version 3.1.1
RUN apt-get -y update &&\
  apt-get -y install openbabel python3-openbabel &&\
  apt-get clean

ENV PYTHONPATH=/code
ENV HOME=/code
WORKDIR ${HOME}

# install our requirements. RDKit is present in base container, OBabel is apt installed earlier
RUN pip install scikit-learn==1.9.1\
  pdb2pqr==3.7.1\
  im-standardize-molecule==0.1.0\
  "im-data-manager-job-utilities>=1.4.0"\
  "im-rdkit-utilities>=1.1.2"\
  sigfig==1.3.19

COPY src/*.py src/fpscores.pkl.gz src/site_substructures.smarts ./
COPY src/moldb/ ./moldb/
