FROM informaticsmatters/obabel:3.1.1

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

ENV PYTHONUNBUFFERED=1

# Do stuff as root
USER 0
WORKDIR /code
COPY --chown=obabel gen_conformer.* ./
RUN chmod 755 *.py

# Finally, return to the obabel user id.
USER obabel
