FROM informaticsmatters/vs-rdkit-base:latest

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

ENV PYTHONPATH=/code
ENV HOME=/code
WORKDIR ${HOME}

# pip install our requirements, including the Neo4j drivers
RUN pip install \
  neo4j-driver==4.4.11 \
  im-standardize-molecule==0.1.0 \
  im-data-manager-job-utilities==1.1.1

COPY fn_*.py utils.py ./

