FROM informaticsmatters/plants:latest

USER 0

RUN apt-get update &&\
  apt-get -y install python3\
    python-is-python3\
    python3-jinja2\
    python3-pip\
    openbabel\
    python3-openbabel &&\
  apt-get clean

RUN pip install im-data-manager-job-utilities==1.0.1

COPY pharmacophore.py utils.py /code/
