FROM informaticsmatters/rdock:2013.1
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

USER 0

RUN yum -y update &&\
    yum -y install python-devel python-jinja2 &&\
    yum clean all

RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org im-data-manager-job-utilities==1.2.0

COPY prepare_rdock.py rdock_*.sh /code/
COPY scripts/*.sh /usr/local/bin/
RUN chmod 755 /code/prepare_rdock.py

USER rdock
