FROM informaticsmatters/plants:latest

USER 0

RUN apt-get update &&\
  apt-get -y install python3\
    python-is-python3\
    python3-jinja2\
    openbabel\
    python3-openbabel &&\
  apt-get clean

COPY pharmacophore.py utils.py /code/
USER 1000