FROM continuumio/miniconda3:4.10.3

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

RUN apt-get -y update &&\
  apt-get -y install procps &&\
  apt-get clean

ENV PYTHONUNBUFFERED=1

ENV HOME=/code
WORKDIR ${HOME}

COPY fn_*.py utils.py ./

# conda install our requirements, including RDKit and Neo4j drivers
RUN conda install -y -c conda-forge pip=21.1.1 rdkit=2021.03.5 neo4j-python-driver=4.4.1 &&\
  pip install im-standardize-molecule==0.1.0 &&\
  conda init bash

