
version: '2.4'


services:

    ################# PostgreSQL container ############################################
    #
    postgres:
        image: informaticsmatters/rdkit-cartridge-debian:Release_2021_03
        volumes:
        - /work/moldb/pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: squonk
        ports:
        - "5432:5432"
        shm_size: '20gb'
        command:
        - "postgres"
        - "-c"
        - "max_wal_size=1GB"
        - "-c"
        - "shared_buffers=16GB"
        - "-c"
        - "work_mem=256MB"
        - "-c"
        - "synchronous_commit=off"
        - "-c"
        - "full_page_writes=off"
