FROM python:3.12.14-slim-trixie

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

RUN apt-get -y update &&\
  apt-get -y install procps &&\
  apt-get clean

ENV PYTHONUNBUFFERED=1

ENV PYTHONPATH=/code
ENV HOME=/code
WORKDIR ${HOME}

RUN pip install matplotlib==3.11.2 sigfig "im-data-manager-job-utilities>=1.4.0"

COPY src/dmpk/*.py ./dmpk/