FROM informaticsmatters/plants:latest

ENV PYTHONUNBUFFERED=1

USER 0

RUN apt-get update &&\
  apt-get -y install python3\
    python-is-python3\
    python3-jinja2\
    python3-pip\
    openbabel\
    python3-openbabel &&\
  apt-get clean

COPY pharmacophore.py utils.py /code/

RUN chmod a+x /code/*.py &&\
    pip install im-data-manager-job-utilities==1.1.1
