FROM continuumio/miniconda3:4.10.3

# Note:     When run by the Data Manager the uid and gid
#           will be set according to the Project we're running against.
#           Consequently we cannot know in advance the user or group id
#           for execution, and so we must ensure the code runs
#           as any user.

RUN apt-get -y update &&\
  apt-get -y install procps &&\
  apt-get clean

ENV PYTHONUNBUFFERED=1

ENV HOME=/code
WORKDIR ${HOME}

COPY *.py *.nf ./

# conda install our requirements, including RDKit and ODDT
RUN conda install -y -c conda-forge pip=21.1.1 rdkit=2021.03.5 oddt=0.7 &&\
  conda init bash

