---
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: DMPK tools
collection: im-dmpk

jobs:
  pk-tmax-cmax-sim:
    name: Estimation of absorption
    description: >-
      Estimation of absorption from t1/2 and Tmax after po administration (one-compartment)
    version: '1.0.0'
    category: dmpk
    keywords:
    - dmpk
    - absorption
    - cmax
    - kel
    image:
      name: informaticsmatters/vs-dmpk
      tag: 'latest'
      project-directory: /data
      working-directory: /data
      fix-permissions: true
    command: >-
      python -m dmpk.pk_tmax_cmax_sim
      --half-life {{ halfLife }}
      --absorption {{ absorption }}
      --dose {{ dose }}
      --auc {{ auc }}
      --time {{ time }}
      --output '{{ outputBaseName }}'
      {% if plotWidth is defined %}--plot-width {{ plotWidth }}{% endif %}
      {% if plotHeight is defined %}--plot-height {{ plotHeight }}{% endif %}
      {% if fontSize is defined %}--font-size {{ fontSize }}{% endif %}
    variables:
      order:
        options:
        - outputBaseName
        - halfLife
        - absorption
        - dose
        - auc
        - time
        - plotWidth
        - plotHeight
        - fontSize
      outputs:
        type: object
        properties:
          pngFile:
            title: PNG file
            mime-types:
            - image/png
            creates: '{{ outputBaseName }}.png'
            type: file
          txtFile:
            title: Text file
            mime-types:
            - text/plain
            creates: '{{ outputBaseName }}.txt'
            type: file
      options:
        type: object
        required:
        - outputBaseName
        - halfLife
        - absorption
        - dose
        - auc
        - time
        properties:
          outputBaseName:
            title: Output file base name
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
            default: output
          halfLife:
            title: Half life (hours)
            type: number
          absorption:
            title: Half life absorption (hours)
            type: number
          dose:
            title: Initial dose (mg)
            type: number
          auc:
            title: AUC (mg/L*hr)
            type: number
          time:
            title: Time (h)
            type: number
          plotWidth:
            title: Plot width (inches)
            type: integer
            default: 10
          plotHeight:
            title: Plot height (inches)
            type: integer
            default: 4
          fontSize:
            title: Find size (points)
            type: integer
            default: 12
    tests:
      simple-execution:
        options:
          outputBaseName: foo/output
          halfLife: 0.79
          absorption: 0.5
          dose: 0.14
          auc: 0.88
          time: 8
          plotWidth: 10
          plotHeight: 4
        checks:
          exitCode: 0
          outputs:
          - name: foo/output.png
            checks:
            - exists: true
          - name: foo/output.txt
            checks:
            - exists: true
            - lineCount: 12
