version: '2.1'

services:

    ################# PostgreSQL container ############################################
    #
    postgres:
        image: informaticsmatters/rdkit-cartridge-debian:Release_2021_03
        environment:
            POSTGRES_PASSWORD: squonk
        ports:
        - "5432:5432"
