---
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: File utility jobs
collection: file-utils

jobs:
  sdf-splitter:
    name: Split SDF file
    description: >-
      Takes a SDF file and splits it into chunks of a specified number of records
    version: '1.0.0'
    category: file utils
    keywords:
    - sdf
    - splitter
    - file
    image:
      name: informaticsmatters/vs-rdock
      tag: latest
      project-directory: /data
      working-directory: /data
      fix-permissions: true
    command: >-
      split-sdf.sh {{ inputFile }} {{ count }} {{ outputFile }}
    variables:
      order:
        options:
        - count
        - outputFile
      inputs:
        type: object
        required:
        - inputFile
        properties:
          inputFile:
            title: SDFile to split
            mime-types:
            - chemical/x-mdl-sdfile
      outputs:
        type: object
        properties:
          outputFile:
            title: Output file base name
            mime-types:
            - chemical/x-mdl-sdfile
            creates: '{{ outputFile }}_*.sdf'
            type: files
      options:
        type: object
        required:
        - count
        properties:
          outputFile:
            title: Output file name
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
            default: chunk
          count:
            title: Chunk size
            type: integer
            minimum: 1

    tests:
      simple-execution:
        inputs:
          inputFile: data/candidates.sdf
        options:
          outputFile: mychunk
          count: 5
        checks:
          exitCode: 0
          outputs:
          - name: mychunk_00001.sdf
            checks:
            - exists: true

  concatenator:
    name: Concatenate files
    description: >-
      Takes a number of input files and concatenates them into a single output file
    version: '1.0.0'
    category: file utils
    keywords:
      - concatenate
      - combine
      - file
    image:
      name: informaticsmatters/vs-prep
      tag: latest
      project-directory: /data
      working-directory: /data
      fix-permissions: true
    command: >-
      python concatenator.py -f '{{ filesGlob }}' -d '{{ dirsGlob }}' {{ outputFile }}
    variables:
      order:
        options:
          - filesGlob
          - outputFile
          - header
          - binary
      outputs:
        type: object
        properties:
          outputFile:
            title: Output files
            creates: '{{ outputFile }}'
            type: files
      options:
        type: object
        required:
          - filesGlob
          - outputFile
        properties:
          filesGlob:
            title: Input files
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-\\?\\*]+$"
          dirsGlob:
            title: Dirs to search
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-\\?\\*]+$"
          outputFile:
            title: Output file name
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
          header:
            title: Handle header line
            type: string
            enum:
              - ignore
              - retain
          binary:
            title: Treat as binary
            type: boolean
            default: false

#    tests:
#      simple-execution:
#        options:
#          outputFile: outfile.smi
#          filesGlob: 10*.smi
#          dirGlob: data
#        checks:
#          exitCode: 0
#          outputs:
#            - name: outfile.smi
#              checks:
#                - exists: true
#                - lineCount: 111110
