---
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: File utility jobs
collection: file-utils

jobs:
  sdf-splitter:
    name: Split SDF file
    description: >-
      Takes a SDF file and splits it into chunks of a specified number of records
    version: '1.0.0'
    category: file utils
    keywords:
    - sdf
    - splitter
    image:
      name: informaticsmatters/vs-rdock
      tag: latest
      project-directory: /data
      working-directory: /data
      fix-permissions: true
    command: >-
      split-sdf.sh {{ inputFile }} {{ count }} {{ outputFile }}
    variables:
      inputs:
        type: object
        required:
        - inputFile
        properties:
          inputFile:
            title: SDFile to split
            mime-types:
            - chemical/x-mdl-sdfile
            type: file
      outputs:
        type: object
        properties:
          outputFile:
            title: Output files
            mime-types:
            - chemical/x-mdl-sdfile
            creates: '{{ outputFile }}_*.sdf'
            type: files
      options:
        type: object
        required:
        - count
        properties:
          outputFile:
            title: Output file name
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
            default: chunk
          count:
            title: Chunk size
            type: integer
            minimum: 1

    tests:
      simple-execution:
        inputs:
          inputFile: data/candidates.sdf
        options:
          outputFile: mychunk
          count: 5
        checks:
          exitCode: 0
          outputs:
          - name: mychunk_00001.sdf
            checks:
            - exists: true
