---
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: MolDB tools
collection: moldb
repository-url: https://github.com/InformaticsMatters/virtual-screening/moldb.yaml
repository-tag: '1.0.0'

test-groups:
- name: experiment-a
  compose-file: docker-compose-moldb.yaml

jobs:
  moldb-create-tables:
    name: Create MolDB database tables
    description: >-
      Create MolDB database tables
    version: '1.0.0'
    category: ligand preparation
    keywords:
    - moldb
    - database
    image:
      name: informaticsmatters/vs-moldb
      tag: 'latest'
      project-directory: /data
      working-directory: /data
      type: nextflow
      environment:
      - name: POSTGRES_USERNAME
        value-from:
          secret:
            name: im-moldb
            key: username
      - name: POSTGRES_PASSWORD
        value-from:
          secret:
            name: im-moldb
            key: password
      - name: POSTGRES_SERVER
        value-from:
          secret:
            name: im-moldb
            key: server
      - name: POSTGRES_DATABASE
        value-from:
          secret:
            name: im-moldb
            key: database
      fix-permissions: true
    command: >-
      python -m moldb.create_db
    variables:
      # no inputs
      # no outputs
      # no options
      options:
        type: object
        properties:
          dummy:
            title: Dummy option
            type: string
    tests:
      create:
        run-groups:
        - name: experiment-a
          ordinal: 1
        environment:
        - POSTGRES_USERNAME
        - POSTGRES_PASSWORD
        - POSTGRES_SERVER
        - POSTGRES_DATABASE
        options:
          dummy: test
        checks:
          exitCode: 0

  moldb-load-library:
    name: MolDB load library
    description: >-
      Load compound library into MolDB, calculating molecular properties
    version: '1.0.0'
    category: ligand preparation
    keywords:
    - moldb
    - database
    - library
    image:
      name: informaticsmatters/vs-moldb
      tag: 'latest'
      project-directory: /data
      working-directory: /data
      type: nextflow
      environment:
      - name: POSTGRES_USERNAME
        value-from:
          secret:
            name: im-moldb
            key: username
      - name: POSTGRES_PASSWORD
        value-from:
          secret:
            name: im-moldb
            key: password
      - name: POSTGRES_SERVER
        value-from:
          secret:
            name: im-moldb
            key: server
      - name: POSTGRES_DATABASE
        value-from:
          secret:
            name: im-moldb
            key: database
      fix-permissions: true
    command: >-
      nextflow -log {{ DM_INSTANCE_DIRECTORY }}/nextflow.log
      run {{ CODE_DIRECTORY|default('/code') }}/moldb/load_library.nf
      -i '{{ input }}'
      --library_name '{{ library }}'
      --name_col {{ id_col }}
      {% if chunk_size is defined %}--chunk_size {{ chunk_size }}{% endif %}
      {% if header is defined and header %}--header{% endif %}
      --delimiter '{{ delimiter }}'
      --interval 10000
      -with-trace {{ DM_INSTANCE_DIRECTORY }}/trace.txt
      -with-report {{ DM_INSTANCE_DIRECTORY }}/report.html
    variables:
      order:
        options:
        - library
        - id_col
        - delimiter
        - header
        - chunk_size
      inputs:
        type: object
        required:
        - input
        properties:
          input:
            title: Molecules to load (.smi)
            mime-types:
            - squonk/x-smiles
            - chemical/x-daylight-smiles
            type: file
      # no outputs
      options:
        type: object
        required:
        - library
        - id_col
        - delimiter
        properties:
          library:
            title: Library name
            type: string
            pattern: "^[A-Za-z0-9][A-Za-z0-9_/\\- ]+$"
          id_col:
            title: Index of ID field (zero based)
            type: integer
            default: 1
          delimiter:
            title: Delimiter
            type: string
            default: tab
            enum:
            - tab
            - comma
            - space
            - pipe
          header:
            title: Skip header line
            type: boolean
            default: false
          chunk_size:
            title: Chunk size for splitting
            type: integer
            default: 100000
            minValue: 10000
            maxValue: 1000000
    tests:
      simple-load:
        run-groups:
        - name: experiment-a
          ordinal: 2
        environment:
        - POSTGRES_USERNAME
        - POSTGRES_PASSWORD
        - POSTGRES_SERVER
        - POSTGRES_DATABASE
        inputs:
          input: data/10000.smi
        options:
          library: test
          id_col: 1
          delimiter: tab
          header: false
          chunk_size: 1000
        checks:
          exitCode: 0
