---
name: build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  schedule:
  # Build every day at 6:01am...
  - cron: '1 6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
    - name: Jote
      run: |
        jote --manifest manifest-fragnet-search.yaml --dry-run --allow-no-tests
        jote --manifest manifest-im-virtual-screening.yaml --dry-run
        jote --manifest manifest-silicos-it.yaml --dry-run --allow-no-tests
        jote --manifest manifest-dmpk.yaml --dry-run
        jote --manifest manifest-im-mordred.yaml --dry-run

  build-prep:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-prep .

  build-nextflow:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-nextflow .

  build-rdock:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-rdock .

  build-smina:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-smina .

  build-oddt:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-oddt .

  build-plants:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-plants .

  build-fragnet-search:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-fns .

  build-jaqpot:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-jaqpot .

  build-moldb:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-moldb .

  build-dmpk:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-dmpk .

  build-mordred:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -f Dockerfile-mordred .
