---
name: build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - 'master'
  schedule:
  # Build daily at 6:01am...
  - cron: '1 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
    - name: Jote
      run: |
        jote --manifest manifest-fragnet-search.yaml --dry-run --allow-no-tests 
        jote --manifest manifest-im-virtual-screening.yaml --dry-run
        jote --manifest manifest-silicos-it.yaml --dry-run --allow-no-tests
    - name: Build
      run: docker-compose build
