---
name: build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
    - name: Jote
      run: |
        jote --manifest manifest-fragnet-search.yaml --dry-run
        jote --manifest manifest-virtual-screening.yaml --dry-run
        jote --manifest manifest-silicos-it.yaml --allow-no-tests --dry-run
