---
name: build-and-push

# A callable workflow to build (and optionally) push container images.

on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        required: true
        default: latest
      image-push:
        type: boolean
        required: false

jobs:
  build-prep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-prep . -t informaticsmatters/vs-prep:${{ inputs.image-tag }}
    - name: Push
      if: ${{ inputs.image-push == true }}
      run: docker push informaticsmatters/vs-prep:${{ inputs.image-tag }}

  build-nextflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-nextflow . -t informaticsmatters/vs-nextflow:${{ inputs.image-tag }}

  build-rdock:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-rdock . -t informaticsmatters/vs-rdock:${{ inputs.image-tag }}

  build-smina:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-smina . -t informaticsmatters/vs-smina:${{ inputs.image-tag }}

  build-oddt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-oddt . -t informaticsmatters/vs-oddt:${{ inputs.image-tag }}

  build-plants:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-plants . -t informaticsmatters/vs-plants:${{ inputs.image-tag }}

  build-fragnet-search:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-fns . -t informaticsmatters/vs-fragnet-search:${{ inputs.image-tag }}

  build-jaqpot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-jaqpot . -t informaticsmatters/vs-jaqpot:${{ inputs.image-tag }}

  build-moldb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-moldb . -t informaticsmatters/vs-moldb:${{ inputs.image-tag }}

  build-dmpk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker build -f Dockerfile-dmpk . -t informaticsmatters/vs-dmpk:${{ inputs.image-tag }}

  build-mordred:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -f Dockerfile-mordred . -t informaticsmatters/mordred:${{ inputs.image-tag }}
