---
name: publish-stable

# Actions that take place on tags.
# Here we build a 'stable' image, regardless of tag value.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches:
    - staging

jobs:
  call-test:
    uses: ./.github/workflows/test.yaml

  call-build-without-push:
    needs: call-test
    uses: ./.github/workflows/build-with-push-option.yaml
    secrets: inherit
    with:
      image-tag: latest
      image-push: true
