---
name: publish-stable

# Actions that take place on tags.
# Here we build a 'stable' image, regardless of tag value.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    tags:
    - '**'

jobs:
  publish-stable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Install docker compose (v2)
      uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.24.0'
    - name: Build and Push
      run: |
        docker compose build
        docker compose push
      env:
        IMAGE_TAG: stable
